name: Node.js CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '14' ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm ci
    - name: Check ESLint
      run: npm run lint
    - name: Run tests
      run: npm test
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}